server:
  port: 8801
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.01
  maxMonry: 9999
  description: 最少要发${limit.minMoney}元,最多不能超过${limit.maxMonry}元

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckymoney?serverTimezone=UTC
    username: root
    password: fuck2!see
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true